local k = require 'utils.keymaps'

k.safe_keymap('n', '<C-n>', vim.cmd.Ex)

--snippets
k.safe_keymap('n', '<leader>ee', 'oif err != nil {<CR>}<Esc>Oreturn err<Esc>', { desc = 'Go error handling' })

k.safe_keymap('n', '<leader>km', '<cmd>Telescope keymaps<cr>', { desc = 'Keymaps' })
k.safe_keymap({ 'n', 'x' }, '<Down>', "v:count == 0 ? 'gj' : 'j'", { desc = 'Down', expr = true, silent = true })
k.safe_keymap({ 'n', 'x' }, '<Up>', "v:count == 0 ? 'gk' : 'k'", { desc = 'Up', expr = true, silent = true })
k.safe_keymap('n', '<Esc>', '<cmd>nohlsearch<CR>')
k.safe_keymap('n', '<leader>sr', [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]], { desc = 'Search & replace' })
k.safe_keymap('n', '<leader>sc', [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gIc<Left><Left><Left>]], { desc = 'Search & replace with confirm' })
k.safe_keymap('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
k.safe_keymap('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
k.safe_keymap('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
k.safe_keymap('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })
k.safe_keymap('n', '<C-Up>', '<cmd>resize +2<cr>', { desc = 'Increase Window Height' })
k.safe_keymap('n', '<C-Down>', '<cmd>resize -2<cr>', { desc = 'Decrease Window Height' })
k.safe_keymap('n', '<C-Left>', '<cmd>vertical resize -2<cr>', { desc = 'Decrease Window Width' })
k.safe_keymap('n', '<C-Right>', '<cmd>vertical resize +2<cr>', { desc = 'Increase Window Width' })
k.safe_keymap('n', '<leader>bd', ':bp | bd #<CR>', { noremap = true, silent = true, desc = 'Delete buffer' })
k.safe_keymap('n', '<S-Tab>', '<cmd>bprevious<cr>', { desc = 'Prev Buffer' })
k.safe_keymap('n', '<BS>', '<C-^>', { noremap = true, silent = true, desc = 'Move to last opened buffer' })
k.safe_keymap('n', '<Tab>', '<cmd>bnext<cr>', { desc = 'Next Buffer' })
k.safe_keymap('n', '<leader>bo', '<cmd>%bd|e#|bd#<cr>', { desc = 'Close all buffers except current' })
k.safe_keymap('n', '<leader>bc', '<cmd>:%bd!<cr>', { desc = 'Close all buffers' })
k.safe_keymap('n', '<leader>l', '<cmd>Lazy<cr>', { desc = 'Open Lazy' })
k.safe_keymap('n', '<C-c>', '"+yy', { desc = 'Copy current line to system clipboard' })
k.safe_keymap('v', '<C-c>', '"+y', { desc = 'Copy to system clipboard' })
k.safe_keymap('n', '<C-P>', '"+p', { desc = 'Paste from system clipboard' })
k.safe_keymap({ 'n', 'v' }, '<A-k>', '<cmd>m .-2<cr>==', { desc = 'Move line up' })
k.safe_keymap({ 'n', 'v' }, '<A-j>', '<cmd>m .+1<cr>==', { desc = 'Move line down' })
k.safe_keymap('i', '<A-k>', '<Esc><cmd>m .-2<cr>==gi', { desc = 'Move line up' })
k.safe_keymap('i', '<A-j>', '<Esc><cmd>m .+1<cr>==gi', { desc = 'Move line down' })
k.safe_keymap('n', '<S-Up>', 'V<Up>', { desc = 'Select up' })
k.safe_keymap('n', '<S-Down>', 'V<Down>', { desc = 'Select down' })
k.safe_keymap('n', '<S-Left>', 'V<Left>', { desc = 'Select left' })
k.safe_keymap('n', '<S-Right>', 'V<Right>', { desc = 'Select right' })
k.safe_keymap('v', '<S-Up>', 'V<Up>', { desc = 'Select up' })
k.safe_keymap('v', '<S-Down>', 'V<Down>$', { desc = 'Select down' })
k.safe_keymap('v', '<S-Left>', 'V<Left>', { desc = 'Select left' })
k.safe_keymap('v', '<S-Right>', 'V<Right>', { desc = 'Select right' })
k.safe_keymap('i', '<S-Up>', '<Esc>V<Up>', { desc = 'Select up' })
k.safe_keymap('i', '<S-Down>', '<Esc>V<Down>$', { desc = 'Select down' })
k.safe_keymap('i', '<S-Left>', '<Esc>V<Left>', { desc = 'Select left' })
k.safe_keymap('i', '<S-Right>', '<Esc>V<Right>', { desc = 'Select right' })
k.safe_keymap('s', '<S-Up>', 'V<Up>', { desc = 'Select up' })
k.safe_keymap('s', '<S-Down>', 'V<Down>$', { desc = 'Select down' })
k.safe_keymap('s', '<S-Left>', 'V<Left>', { desc = 'Select left' })
k.safe_keymap('s', '<S-Right>', 'V<Right>', { desc = 'Select right' })
k.safe_keymap('n', 'mm', 'mM', { desc = 'Mark file' })
k.safe_keymap('n', 'M', '`M', { desc = 'Jump to marked file' })
k.safe_keymap('n', '<C-a>', 'gg<S-v>G', { desc = 'Select all' })
k.safe_keymap('i', '<C-a>', '<Esc>gg<S-v>G', { desc = 'Select all' })
k.safe_keymap({ 'i', 'x', 'n', 's' }, '<C-s>', '<cmd>w<cr><esc>', { desc = 'Save File' })
k.safe_keymap('n', '<leader>a', '<cmd>cadd %<cr>', { desc = 'Add to Quickfix List' })
k.safe_keymap('n', '<leader>p', vim.cmd.cprev, { desc = 'Previous Quickfix' })
k.safe_keymap('n', '<leader>n', vim.cmd.cnext, { desc = 'Next Quickfix' })
