[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 } 
dynamic_padding = false
decorations = "Full"
opacity = 0.65
startup_mode = "Windowed"
position = { x = 240, y = 240 }

class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "Dark"

[scrolling]
history = 5000
multiplier = 1 

[font]
size = 9.5
builtin_box_drawing = true

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 5

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = false

[bell]
animation = "Linear"
duration = 0

[cursor]
unfocused_hollow = true
thickness = 0.1

[cursor.style]
shape = "Block"
blinking = "Never"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[terminal]
shell = { program = "/usr/bin/zsh" }


